### ISSUE TITLE
Cannot run wdtk-examples

### ISSUE THREAD

**Issue by bolatov** [Wikidata/Wikidata-Toolkit#118]
Hello,

I have problems running example classes [EntityStatisticsProcessor](https://github.com/Wikidata/Wikidata-Toolkit/blob/master/wdtk-examples/src/main/java/org/wikidata/wdtk/examples/EntityStatisticsProcessor.java), [JsonSerializationProcessor](https://github.com/Wikidata/Wikidata-Toolkit/blob/master/wdtk-examples/src/main/java/org/wikidata/wdtk/examples/JsonSerializationProcessor.java). Eclipse cannot organize imports, although the *latest* version (0.3.0) from maven is used.

Should the github version be used to run the code or is there already a newer version of the WikidataToolkit?

**Comment by mkroetzsch** [comment]
Right now you need to use the github version. We will have a new release soon. The problems that occur in 0.3.0 should all be fixed in the current github master branch.
