### ISSUE TITLE
Include rank in RDF

### ISSUE THREAD

**Issue by nik9000** [Wikidata/Wikidata-Toolkit#120]
It'd be useful to have the rank included for statements.  It'd allow more fun reasoning.

I can implement this if you have a for how the resulting RDF should look.

**Comment by mkroetzsch** [comment]
Agreed. This should be a small change. I would suggest to have all ranks included using a suitable RDF task, so that people can configure the inclusion of this data when making exports with the command-line client.

**Comment by mkroetzsch** [comment]
Fixed by merging #134
