### ISSUE TITLE
DumpProcessingController.processDumpFile() can not handle null, but may be passed one

### ISSUE THREAD

**Issue by fer-rum** [Wikidata/Wikidata-Toolkit#122]
**Problem Description:**
The code in question is in *DumpProcessingController.processMostRecentDump (line 454)* as follows:
````java
MwDumpFile dumpFile = wmfDumpFileManager.findMostRecentDump(dumpContentType);
processDumpFile(dumpFile, dumpFileProcessor);
````

The first line might evaluate to *null*, as it is also documented. But when *processDumpFile()* is been passed a *null* as the first argument, it throws a *NullPointerException*.

**Suggested Resolution:**
Check the value of *dumpFile* beforehand. If it is *null* abort the processing with an error.

**Comment by mkroetzsch** [comment]
Please check if you are using master. I think this was fixed already. At least this code is not on the line number you mention right now.

**Comment by fer-rum** [comment]
Indeed it is fixed in the code already, I wonder what is wrong with the version I checked out…
