### ISSUE TITLE
Wikibase API: support wbgetentities for more than 50 entities

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/Wikidata-Toolkit#130]
By default, the Wikibase API only returns at most 50 entities via wbgetentities (for anonymous users). The WDTK API implementation currently ignores this limit. It should be modified to split bigger lists into several request (merging the results into one result list).

**Comment by wetneb** [comment]
I think this was fixed by b4179bacc81c3bad5aaee97329034332f99a65ea:
https://github.com/Wikidata/Wikidata-Toolkit/blob/283f4f18813c05e906fcfa1f8daa220d50c2c208/wdtk-wikibaseapi/src/main/java/org/wikidata/wdtk/wikibaseapi/WikibaseDataFetcher.java#L167-L187
