### ISSUE TITLE
WebResourceFetcher returns EmptyInputStream

### ISSUE THREAD

**Issue by bolatov** [Wikidata/Wikidata-Toolkit#155]
Recently my code, that worked before, stopped fetching urls. By debugging I found out that `webRecourceFetcher.getInputStreamForUrl()` returns EmptyInputStream. However, querying the `url` in the web browser results in a correct json response.

Here is the code to reproduce the bug:
```java
String url = "http://www.wikidata.org/w/api.php?action=wbsearchentities&language=en&search=angela&type=item&limit=50&format=json";
WebResourceFetcher webResourceFetcher = new WebResourceFetcherImpl();
InputStream inputStream = webResourceFetcher.getInputStreamForUrl(url);
String response = IOUtils.toString(inputStream);
System.out.printf("response = '%s'", response); // response = ''
```

**Comment by mkroetzsch** [comment]
This happens because our code does not follow redirects. The http URLs of all Wikimedia sites have recently been switched to https URLs. If you change your URL to https, it will also work for now. The task of adding redirect support is tracked at #151, so I close this as a duplicate.
