### ISSUE TITLE
Sitelinks start with http:https://, e.g., in RDF exports

### ISSUE THREAD

**Issue by igm** [Wikidata/Wikidata-Toolkit#163]
The RDF dump contains lines like:
```
<http:https://en.wikipedia.org/wiki/Universe> <http://schema.org/about> <http://www.wikidata.org/entity/Q1> .
```
I'm not sure ```http:https``` is a correct form of IRI. But I'd rather ask here before digging into implementation details and creating a PR. To my understanding the IRI should be in format as specified in RFC https://www.ietf.org/rfc/rfc3987.txt and it does not allow ```schema:schema``` tokens.

**Comment by mkroetzsch** [comment]
That's a bug. Thanks for reporting it. We will look into it.

**Comment by mkroetzsch** [comment]
It turns out that this bug was not specific to the RDF export but affected all uses of sitelinks in Wikidata Toolkit. The fix now merged in master corrects this.
