### ISSUE TITLE
Basic dictionary implementation

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/Wikidata-Toolkit#19]
A basic implementation for a dictionary of String-identified objects should be provided. This component needs to assign integer ids to incoming String ids, and it must manage a bijective mapping that allows to access either type of id when providing the other. Space efficiency is a primary concern, but a workable speed must also be given.

**Comment by wetneb** [comment]
Closing this as stale, feel free to revert if this still fits in some relevant milestone.
