### ISSUE TITLE
The RDF format is incorrect

### ISSUE THREAD

**Issue by monkey2000** [Wikidata/Wikidata-Toolkit#199]
Many bug trackers of RDF Databases have been report this bug.
> \"-escape sequences are not allowed in URIs, only \u

Apache Jena: https://issues.apache.org/jira/browse/JENA-806
Google Cayley: https://github.com/google/cayley/issues/256

**Comment by mkroetzsch** [comment]
Thanks. We do not do any URL encoding in Wikidata Toolkit, but rely on OpenRDF for this. It seems that there are some bugs there. We ls have another issue in this space: #133

**Comment by mkroetzsch** [comment]
I just checked, and eventually the URI object used to export this data is created by calling the method
```
org.openrdf.model.ValueFactory#createURI(string)
```
where the URI string is obtained as follows:
```
"http://commons.wikimedia.org/wiki/File:" + pageName.replace(' ', '_');
```
pageName here is the literal Wikipedia page name. It may contain weird characters in many cases, but no character escapes. It seems that OpenRDF accepts this input and does not throw any exception. The resulting URI object is eventually used in a triple ("statement" object in OpenRDF) and serialized ("handled") by an OenRDF Writer for RDFFormat.NTRIPLES. It really seems to be a bug in OpenRDF that this leads to malformed RDF.

**Comment by monkey2000** [comment]
This bug is fixed. (As a workaround)
