### ISSUE TITLE
Wikibase interface to storage backend

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/Wikidata-Toolkit#20]
A component for exchanging Wikibase objects, especially EntityDocuments, with a storage backend should be provided. The mapping of ids will use a dictionary #19 and data will be stored in tuples using one or more "tables" #18. The interface should also provide some basic query features to retrieve Wikibase objects based on partially specified features.

**Comment by wetneb** [comment]
Closing this as stale, feel free to revert if this still fits in some relevant milestone.
