### ISSUE TITLE
Export best rank

### ISSUE THREAD

**Issue by guenthermi** [Wikidata/Wikidata-Toolkit#203]
Add triples to declare that a statement is one of the statements with the highest rank like

 wds:Q42-11725e9f-4f81-e0fd-b00a-b885fe7a75ac a wikibase:BestRank .

**Comment by pfps** [comment]
An alternative would be to have a version of the simple export that only includes highest-rank statements.

**Comment by Tpt** [comment]
Done and released following the same pattern as the Wikibase APi and dumps
