### ISSUE TITLE
Apdapt statement representation

### ISSUE THREAD

**Issue by guenthermi** [Wikidata/Wikidata-Toolkit#205]
- change the URIs for statements (e.g. http://www.wikidata.org/entity/Q1Sf5d5115d-489a-7654-9a0a-5eea5be80d07 to http://www.wikidata.org/entity/statement/Q1-Sf5d5115d-489a-7654-9a0a-5eea5be80d07)
- change property URIs (e.g. http://www.wikidata.org/entity/P1036v to http://www.wikidata.org/prop/statement/P103)
- change references (e.g. http://www.wikidata.org/entity/R5e7085d5edead456aa182bc481944261 to http://www.wikidata.org/reference/5e7085d5edead456aa182bc481944261)
- change http://www.wikidata.org/entity/P31s to http://www.wikidata.org/prop/P31

**Comment by Tpt** [comment]
Done and released
