### ISSUE TITLE
Apapt value representation

### ISSUE THREAD

**Issue by guenthermi** [Wikidata/Wikidata-Toolkit#207]
Change the representation of the values. There should be always simple values. Depending on the type of the value there should be a complex version of the value as well. 

e.g.

wds:q42-D8404CDA-25E4-4334-AF13-A3290BCD9C0F
    ps:P569 "1952-03-11T00:00:00Z"^^xsd:dateTime ;
    psv:P569 wdv:426df9023763f08b066f4478480f44cd ;

wdv:426df9023763f08b066f4478480f44cd a wikibase:TimeValue ;
    wikibase:timeValue "1952-03-11T00:00:00Z"^^xsd:dateTime ;
    wikibase:timePrecision "11"^^xsd:integer ;
    wikibase:timeTimezone "0"^^xsd:integer ;
    wikibase:timeCalendarModel http://www.wikidata.org/entity/Q1985727 .

**Comment by Tpt** [comment]
Done and released
