### ISSUE TITLE
Leftover phpinfo file on labs

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/Wikidata-Toolkit#216]
We have a leftover file on the Wikimedia Labs RDF export site:

http://tools.wmflabs.org/wikidata-exports/tmp/test.php

(Reported at
https://www.wikidata.org/wiki/Wikidata:Contact_the_development_team#Useless_phpinfo.28.29_File)

**Comment by guenthermi** [comment]
Thank you for the report. By now all leftover files should be deleted / moved.
