### ISSUE TITLE
DEPRECATION: Removal of lgtoken, cookieprefix, and sessionid response values from action=login

### ISSUE THREAD

**Issue by ricordisamoa** [Wikidata/Wikidata-Toolkit#224]
Please read https://lists.wikimedia.org/pipermail/mediawiki-api/2015-December/003677.html about the deprecated values.
https://github.com/Wikidata/Wikidata-Toolkit/blob/7ebbc7a903c178a3030612c413668edbc52fbfe8/wdtk-wikibaseapi/src/test/resources/loginSuccess.json seems to expect them, but they are going to be removed in MediaWiki 1.28.

**Comment by mkroetzsch** [comment]
Thanks for this hint. We followed this thread and concluded that this change does not affect our code. We use "lgtoken" but only as a parameter, not as a response value, and this usage is still correct, it seems.
