### ISSUE TITLE
RDF Dumps generated with an outdated Wikidata-Toolkit?

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/Wikidata-Toolkit#225]
It has been reported that our RDF exports still contain errors that are fixed in WDTK. See [bug report on talk page](https://www.wikidata.org/w/index.php?title=Wikidata:Contact_the_development_team#RDF_Dumps_are_using_a_outdated_Wikidata-Toolkit.) ([permanent historic link](https://www.wikidata.org/w/index.php?title=Wikidata:Contact_the_development_team&oldid=288111571#RDF_Dumps_are_using_a_outdated_Wikidata-Toolkit.)).

**Comment by JeroenDeDauw** [comment]
The WDTK exports contain error that are fixed in WDTK? huh?

**Comment by mkroetzsch** [comment]
@JeroenDeDauw  The original comment on the talk page is not specific about which problems have been encountered in which dumps, but the link to closed bug reports suggests that the problems might have been the ones fixed before. This still needs to be confirmed though. If we are using the current WDTK for dump generation and the problem still occurs, then we will need more details to do anything about it.

**Comment by monkey2000** [comment]
I'm the original reporter of this bug on talk page. And as my observations, these RDF Dump cannot be used. Hopefully it will be fixed soon.

**Comment by monkey2000** [comment]
Emm...
I reported this bug on Issue #199. And it wasn't deployed in that time.

**Comment by mkroetzsch** [comment]
Yes, we had a bit of a lag in deploying updated code at Wikimedia Labs, due to an oversight on our part. Can you confirm that the new dumps are working now?

**Comment by monkey2000** [comment]
I'm prepare for my senior entrance exam, and I may not check this instantly...
I just put the dump to RDF Database(Apache Jena) and it complained about incorrect rdf syntax.

**Comment by monkey2000** [comment]
And I have an idea about deployment tracking, create a tracker issue and link new received PR to it. Once the new release have deployed, close the tracker issue. And then all contributor will noticed it.

**Comment by mkroetzsch** [comment]
Closing this issue, since it was presumably fixed as explained above.

**Comment by monkey2000** [comment]
I checked out the rdf dumps just now, it's fixed. @mkroetzsch
