### ISSUE TITLE
Make API URL configurable

### ISSUE THREAD

**Issue by lucylw** [Wikidata/Wikidata-Toolkit#236]
At `wdtk-wikibaseapi/src/main/java/org/wikidata/wdtk/wikibaseapi/ApiConnection.java:205`, it seems the API address is hard-coded in as `URL_WIKIDATA_API`. This means the client only works with the canonical WikiData website.

Can you make this API address configurable? It would allow the tools to be used with other WikiBase instances. Thanks!

**Comment by mkroetzsch** [comment]
The method you refer to is called getWikidataApiConnection() and it returns an ApiConnection that is preconfigured for Wikidata. You can als create an ApiConnection by using the normal constructor, which will accept the URL of the API as a parameter. Wikidata Toolkit usually has convenience methods to simplify things for Wikidata, but it should not be specific to Wikidata in many places.

Does this solve your problem?

**Comment by Tpt** [comment]
It is configurable in the newest releases
