### ISSUE TITLE
Merge Statement and Claim interfaces

### ISSUE THREAD

**Issue by Tpt** [Wikidata/Wikidata-Toolkit#242]
They have been merged in WikibaseDataModel a year ago.

**Comment by mkroetzsch** [comment]
WDTK does not attempt to be structurally the same as the PHP implementation of Wikibase.

**Comment by thiemowmde** [comment]
We merged the classes in the PHP data model mostly to avoid the unnecessary complexity of nested `new Statement( new Claim( … ), … )` constructors. If the additional complexity, performance and memory implications of an additional `Claim` object for each `Statement` object is not a problem for this code base, there is no need to get rid of it. The two Java and PHP implementations are not identical anyway, and don't need to.

**Comment by mkroetzsch** [comment]
The memory implications are not an issue for us (the JSON-based object model in WDTK internally is similar to the JSON structure; it just has the interfaces separated). Regarding simplicity, it is true that a nested constructor might be less convenient, but we have convenience factory methods in WDTK to create statements with less work to circumvent this. Changing the interfaces now would make existing code illegal, which I consider the bigger issue for the convenience of our users. I would rather add more convenience shortcut methods if desired, to keep the code as slim as possible.

I am therefore closing this now, but remain open for suggestions on how to simplify WDTK code for developers.
