### ISSUE TITLE
Makes QuantityValue bounds optional

### ISSUE THREAD

**Issue by Tpt** [Wikidata/Wikidata-Toolkit#246]
upper and lower bounds of QuantityValues are becoming optional in Wikibase.
We should apply this change in order to still be compatible with new dumps.

See:
- https://phabricator.wikimedia.org/T115269
- https://lists.wikimedia.org/pipermail/wikidata-tech/2016-November/001050.html

**Comment by mkroetzsch** [comment]
Agreed. However, I am traveling most of next week, so I will most likely not have a chance to work on this so soon.

**Comment by Tpt** [comment]
If you want, I could submit a pull request. What do you thing about doing the same thing as PHP implementation i.e. introduce an UnboundedQuantityValue interface and make QuantityValue extend it? See:
* https://github.com/DataValues/Number/blob/master/src/DataValues/UnboundedQuantityValue.php
* https://github.com/DataValues/Number/blob/master/src/DataValues/QuantityValue.php

**Comment by Tpt** [comment]
An other possible implementation: allows upper and lower bound to be both null at the same time. But it may leads to NullPointerExceptions in the code that relies on upper/lower bounds.

**Comment by JeroenDeDauw** [comment]
> UnboundedQuantityValue interface and make QuantityValue extend it

Huh wtf... if I'm understanding that correctly, it's a very clear https://en.wikipedia.org/wiki/Liskov_substitution_principle violation

**Comment by Tpt** [comment]
> it's a very clear https://en.wikipedia.org/wiki/Liskov_substitution_principle violation
Imho no, it's more a bad naming problem. Because the "UnboundedQuantityValue" is a value with an unknown precision interval, not a value in which precision interval does not make sense. So I think we could state that "QuantityValue" are "UnboundedQuantityValue".

But I agree with you that it's not a nice implementation and I hope that we will be able to find something better.

**Comment by mkroetzsch** [comment]
I would prefer the simple solution of allowing null values for the bounds. I expect the amount of exceptions that this will cause in practice to be low, since there are presumably few real uses of these bounds at the moment. One would have to change the JSON serialisation/deserialisation accordlngly, and possibly update the creation/factory methods.

**Comment by Tpt** [comment]
> I would prefer the simple solution of allowing null values for the bounds.
Ok! I'm going to work on a pull request.

**Comment by mkroetzsch** [comment]
Many thanks!
