### ISSUE TITLE
Failled to fetch and print entity q43

### ISSUE THREAD

**Issue by noyessie** [Wikidata/Wikidata-Toolkit#250]
I'm used wikidata toolkit, but I have the problems to fetch some entities. for example, when i trying to get entity q43, the method `getEntityDocument` work fine, but I can't use or print it.

this is my source code:

import org.wikidata.wdtk.datamodel.interfaces.EntityDocument;
import org.wikidata.wdtk.datamodel.interfaces.ItemDocument;
import org.wikidata.wdtk.wikibaseapi.WikibaseDataFetcher;
import org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException;

public class FetchOnlineDataExample {

    public static void main(String[] args) throws MediaWikiApiErrorException {

        WikibaseDataFetcher wbdf = WikibaseDataFetcher.getWikidataDataFetcher();
        EntityDocument q43 = wbdf.getEntityDocument("Q43"); 
        System.out.println(q43);

    }
}

I have got the xeception:
`java.lang.NullPointerException`

What is the problems, please.

**Comment by guenthermi** [comment]
Can you provide the full trace. I tried out the code by myself and it worked. Do you use the code from the master branch or one of the maven releases?

**Comment by noyessie** [comment]
master branch.

**Comment by luisenriqueramos1977** [comment]
I have done that only adding .toString and I get all doc edited with content

**Comment by wetneb** [comment]
Closing then!
