### ISSUE TITLE
insufficiently initialised statement/claim.

### ISSUE THREAD

**Issue by noyessie** [Wikidata/Wikidata-Toolkit#251]
Please I had got this issue:

    Exception in thread "main" java.lang.RuntimeException: Cannot retrieve subject for insufficiently initialised statement/claim. at org.wikidata.wdtk.datamodel.json.jackson.JacksonStatement.getSubject(JacksonStatement.java:145)`

This is my source code:

    WikibaseDataFetcher wbdf = WikibaseDataFetcher.getWikidataDataFetcher();
    wbdf.getFilter().setLanguageFilter(Collections.singleton("en"));
    wbdf.getFilter().setSiteLinkFilter(Collections.<String> emptySet());
    EntityDocument ed = wbdf.getEntityDocument("Q42");

    System.out.println("++"+ ed + "instance : ");
    //this method uses ObjectMapper mapper = new ObjectMapper(); to write entity in file
    Utils.mapAndWriteToFile(Params.ENTITIES_WITH_RELATIONS+"test.neosoft", 
            ed, EntityDocument.class);

    String ambigus_entities_table[] = Utils.openFile(Params.ENTITIES_WITH_RELATIONS+"test.neosoft").split("[\\n]");
    System.out.println("content: " + ambigus_entities_table[0]);

    //this method the content of last file and uses ObjectMapper mapper = new ObjectMapper(); to create entity object
    JacksonItemDocument itemj = readFromFile(ambigus_entities_table[0]);
            System.out.println("ligne " + 0 + " " + itemj + " class : " + itemj.getClass());

**Comment by guenthermi** [comment]
I can not comprehend the error. Probably you can provide some additional information. What is the content of the ambigus_entities_table and what exactly is the response of readFromFileCan(ambigus_entities_table[0])?

**Comment by Tpt** [comment]
It shouldn't be possible anymore to experience such problems in the version 0.9 of the library.
