### ISSUE TITLE
Extending StatementUpdate

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#274]
I am trying to extend [StatementUpdate](https://github.com/Wikidata/Wikidata-Toolkit/blob/master/wdtk-wikibaseapi/src/main/java/org/wikidata/wdtk/wikibaseapi/StatementUpdate.java#L47) to support updating terms too (labels, descriptions and aliases). The simplest way to do that as a user seems to be to inherit from that class and add the required functionality on top of that.

However, I run into an issue when generating the JSON of the change. Naturally, I would expect to just call [`StatementUpdate.getJsonUpdateString`](https://github.com/Wikidata/Wikidata-Toolkit/blob/3541b49e0961af0d4e754e64904d06e29766f684/wdtk-wikibaseapi/src/main/java/org/wikidata/wdtk/wikibaseapi/StatementUpdate.java#L100-L130) and extend the JSON payload it returns. I was horrified to discover that its implementation generates JSON manually, with a StringBuilder… I am not a Java wizard, but surely there must be better ways to generate JSON than that? I would expect the conversion to String to happen much later downstream (like, just before the HTTP request is performed, ideally), which would make it possible to extend the JSON object easily.

So, what should I do?
- Keep my current approach, just call `StatementUpdate.getJsonUpdateString`, remove the last character (`}`) of the JSON payload and append the rest of the content of the JSON object with a StringBuilder. As far as I can tell this is a nasty hack.
- Parse the String returned by `StatementUpdate.getJsonUpdateString` with some library, add my labels, descriptions and aliases cleanly via this library, and convert the result back to a String (to preserve consistency of the interface with `StatementUpdate`). That's a bit cleaner but it feels really wrong.
- Rewrite `StatementUpdate` (and its users) so that it exposes a cleaner interface (so, make a PR). That's a lot more work. What library should I use? Jackson? Org.json?

**Comment by Tpt** [comment]
Please do a PR to clean that up. Jackson is already used by the datamodel so it would allow us to avoid one extra dependency.
A PR that allows to update labels, descriptions and aliases too is definitely welcome too. We may want to move out from having every parameter in the constructor to something like

`(new ItemUpdate(new ItemId("Q2"))).addStatement(foo).removeLabel(label).save(connection)` with ItemUpdate build by composition from StatementDocumentUpdate, TermedDocumentUpdate...

**Comment by wetneb** [comment]
@Tpt I have considered changing the constructor as you suggested but I think it would be more appropriate to use a separate Builder class for that - as far as I can tell the current update mechanisms are not really designed to be called incrementally. But I agree it would be nicer to have that syntax indeed!

**Comment by Tpt** [comment]
Yes, a Builder is a great idea!
I was a bit ambitious with my syntax because the .save function would have a lot of parameters (bot flag, edit summary...)
