### ISSUE TITLE
Examples no longer functioning after update 0.8.0

### ISSUE THREAD

**Issue by bantat** [Wikidata/Wikidata-Toolkit#280]
Example classes such as 'LifeExpectancyProcessor.java' no longer compile following the new update. Errors produced are of the form "package org.wikidata.wdtk.[package] does not exist", which makes me think POM files need to be updated to reflect changes for version 0.8.0

**Comment by Tpt** [comment]
Thank you very much for the bug report. I have only updated the changelogs for the future 0.8.0 version. The version is not released yet (I do not have the credential to do it so I am waiting for the person having them to do the release). The latest published version is still the 0.7.0. Sorry for the troubles.

**Comment by Tpt** [comment]
I just released version 0.8.0. Hopefully examples are going to work new. Feel free to open this task again if it is not the case. Sorry for the trouble.
