### ISSUE TITLE
Unable to login with latest .jar release

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [Wikidata/Wikidata-Toolkit#282]
#271 has the solution, but  a new .jar file needs to be compiled to make it available for use with jython.

**Comment by wetneb** [comment]
yes we are aware of that, we are working on releasing a new version of the toolkit.

**Comment by PolyglotOpenstreetmap** [comment]
version 0.7.0 has a critical bug. Anybody using those jar files is going to waste precious time trying to figure out why they can't edit, or they will give up on the toolkit, convinced it doesn't work.
Why is no 0.7.1 version coming out?
Sorry for not being 'extremely' patient, like I promised I would.  A message a week doesn't seem to be too bad.

**Comment by wetneb** [comment]
@PolyglotOpenstreetmap I unfortunately do not have the required permissions on this repository to make this happen. @Tpt @mkroetzsch @lydiapintscher

**Comment by PolyglotOpenstreetmap** [comment]
It works now, thanks
