### ISSUE TITLE
ItemDocument.findStatement(P31) returns null when it shouldn't

### ISSUE THREAD

**Issue by yuval** [Wikidata/Wikidata-Toolkit#286]
Wikidata-Toolkit release 0.7.0. Wikidata dump: wikidata-20170703-all.json.gz.

I'm parsing a dump skipping entities with missing instance-of (P31). I noticed it skipped a few entities that actually have the P31 property. 
For example, it skipped Q23215 (Adele). I debugged it and found that ```ItemDocument.findStatement("P31")``` returns null even though ```ItemDocument``` contains ```claims``` with ```key=P31``` and two values ```Q5``` and ```Q2985549```. The first value also has a reference.

**Comment by wetneb** [comment]
I suspect that was linked to the way the siteIRI was passed on to child values, which influences equality checks on property ids. I would expect this bug to be solved by the new implementation.

**Comment by robertvazan** [comment]
Is this fixed? Can this be closed?

**Comment by wetneb** [comment]
Actually my interpretation of this bug was wrong: the problem is just that `findStatement` returns `null` if there are none **or multiple** matching statements. So this was the expected behaviour of the API (it is documented as such).
