### ISSUE TITLE
How can I copy ItemDocument to my own wikidata base?

### ISSUE THREAD

**Issue by sstdz** [Wikidata/Wikidata-Toolkit#288]
Can I take, for example, Q410 item from https://www.wikidata.org/wiki/Q410 and to copy it in my own wikidata base? I tried use
```
DataObjectFactory factory = new DataObjectFactoryImpl();
DatamodelConverter converter = new DatamodelConverter(factory);
ItemDocument itemDocument = converter.copy((ItemDocument) entity);
editor.createItemDocument(itemDocument, "summary");
```
but it only copies itemDocument, not changing the base, where it was created.
Please, sorry that I use "Issues" for questions, the community of toolkit is not big yet and this is very important for me.

**Comment by Tpt** [comment]
It should work if you setup correctly the `editor`by giving it the URI of your wiki. You should also convert all Item and property ids to point to the existing items and properties in your wiki and not the one of Wikidata.

**Comment by sstdz** [comment]
Can you please to give an advice, what structures should I use to convert all Items and Properties from itemDocument?

**Comment by Tpt** [comment]
You should probably create a new ItemDocument from scratch (using the Datamodel class) and add to it only the data you want to have  imported. And when adding a statement you should convert the item/property ids from the ones in Wikidata to the ones in your local wiki (maybe by creating new items/properties in your local wiki)

**Comment by sstdz** [comment]
Thank you a lot! Please, the last one question:
How can I put a ItemIdValue in constructor of DataModel, if I do not know, which number will be given to it by wikidata api? Are there any mechanism that allows to generate id, looking which numbers are already existing in wikidata ?

**Comment by Tpt** [comment]
> Are there any mechanism that allows to generate id, looking which numbers are already existing in wikidata ?

No, the id attribution is done when you create a new item using the Wikibase API. You could use ItemIdValue.NULL as a placeholder when you build the ItemDocument for the item you want to create.

**Comment by sstdz** [comment]
Super, many thanks to you!
