### ISSUE TITLE
How I can to detect, what language throws MediaWikiApiErrorException ?

### ISSUE THREAD

**Issue by sstdz** [Wikidata/Wikidata-Toolkit#294]
Hey! 
Does somebody know, when I am getting exception
`org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [not-recognized-language] The supplied language code was not recognized.`
can I to get an info about what language is a problem ?
Thanks!

**Comment by assafko** [comment]
you need to set language in toolkit init phase e.g

 WikibaseDataFetcher wikidataDataFetcher = WikibaseDataFetcher.getWikidataDataFetcher();
        wikidataDataFetcher.getFilter().setSiteLinkFilter(Collections.singleton("enwiki"));
        wikidataDataFetcher.getFilter().setLanguageFilter(Collections.singleton("en"));
        Set<PropertyIdValue> propertyFilter = Arrays.stream(Relations.values())
                .map(Relations::getPid)
                .map(Datamodel::makeWikidataPropertyIdValue)
                .collect(Collectors.toSet());
        wikidataDataFetcher.getFilter().setPropertyFilter(propertyFilter);

**Comment by sstdz** [comment]
But what if I want to get all languages, not some strict defined ? And some from them are throwing this exception, how I can to detect them ?

**Comment by assafko** [comment]
i think you have to specify them in init. see all possible codes https://www.wikidata.org/wiki/Help:Wikimedia_language_codes/lists/all

**Comment by sstdz** [comment]
Thanks, I just made a filter which looks, is the language from list you sent
