### ISSUE TITLE
Can I find an EntityDocument in public wikidata, having only aliases, labels, descriptions?

### ISSUE THREAD

**Issue by sstdz** [Wikidata/Wikidata-Toolkit#297]
For example: using label + description pair (because it is unique, like I understand)

**Comment by assafko** [comment]
you can try to compose a sparql which search query for wikiid by aliases eyc e.g https://query.wikidata.org/

**Comment by sstdz** [comment]
And maybe you know, is it real to use this mechanism via Wikidata Toolkit API?

**Comment by assafko** [comment]
i would say no. use https://query.wikidata.org/
to compose search manually this automate via jena
and apache Jena https://jena.apache.org/documentation/query/ for execution

**Comment by sstdz** [comment]
Super, thanks a lot !
