### ISSUE TITLE
How to change a datatype of existing property document?

### ISSUE THREAD

**Issue by sstdz** [Wikidata/Wikidata-Toolkit#298]
I had a look at PropertyDocumentBuilder to find the method for this goal, like "withDatatype", but there are no such one. You only can to initialize a PropertyDocumentBuilder with right one, but when I update it there are no any changes. I mean I tried something like:
```
WikibaseDataEditor wikibaseDataEditor = ...
PropertyDocumentBuilder builder = PropertyDocumentBuilder.forPropertyIdAndDatatype(idOfPropertyNeedToChange, newDatatype);
wikibaseDataEditor.editPropertyDocument(builder.build(), false, "summary");
```
Are there an opportunity to replace datatype ?

**Comment by Tpt** [comment]
Wikibase does not allow to change the datatype of a property. You could not do it except by editing manually the wiki SQL database. So, it is not possible to add this feature to WikidataToolkit.

**Comment by sstdz** [comment]
Thank for your answer!
