### ISSUE TITLE
0.0.7 seems not to work at all anymore

### ISSUE THREAD

**Issue by WolfgangFahl** [Wikidata/Wikidata-Toolkit#299]
The following JUnit test fails in my environment with 0.0.7 and Java 8.
With 0.0.8-SNAPSHOT it works so a 0.0.8 release would be most welcome.

```
 @Test
  public void testWikiDatabaseFetcher() throws MediaWikiApiErrorException {
    WikibaseDataFetcher wbdf = WikibaseDataFetcher.getWikidataDataFetcher();
    System.out.println("*** Fetching data for entity Q42:");
    EntityDocument q42 = wbdf.getEntityDocument("Q42");
    assertNotNull(q42);
}
```

**Comment by Tpt** [comment]
Yes, I plan to do this release but for that I need to work with the people having access to the Maven Central account. I have opened a task about it: #300
