### ISSUE TITLE
Editing EntityDocument instances locally

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#310]
I have been working on the wikibaseapi module to add a new editing feature: selecting the appropriate API action based on the contents of the change. Instead of using "wbeditentity" every time, the goal is to use the most specific action instead (such as "wbsetaliases" if the change is only about aliases in one language). The main advantage of this is that we get more meaningful edit summaries, which are localized by Wikibase, while still providing the same uniform interface (TermStatementUpdate) to the developer. You can get a glimpse of what it looks like in action here:
https://www.wikidata.org/wiki/Special:Contributions/PintochBot

I am not submitting a PR for this yet because I still have one issue to resolve. The nice thing about "wbeditentity" is that the response contains the new state of the item, which you do not get if you do a more specific action (you only get what you modified). The WikibaseDataEditor class currently returns the new state of the edited item as an EntityDocument, so if we want to keep this behaviour, I need a way to update an existing instances EntityDocument with the changes that have been performed remotely. But currently, the java classes and interfaces seem to be design to forbid that. One way to do it is to convert the existing instance to a Jackson instance and use the setters on it, but it's a hack.

So, my question is: how do I copy an EntityDocument and change some of its properties?

Of course one way to do this would be a simple wbgetentities but it is sad to make an additional query when we have all the required information locally. The simplest way I can think of (or least hacky, say) would be to update the Builder classes to accept an initial document to start the build from.

@Tpt thoughts?

**Comment by Tpt** [comment]
A possible idea would be to change `EntityDocumentBuilder` to have a factory method taking for input parameter an EntityDocument and returning the relevant builder  (i.e. `PropertyDocumentBuilder` and `ItemDocumentBuilder`) filled with the entity content.
