### ISSUE TITLE
Why two different implementations of the data model?

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#318]
Dear WDTK maintainers, it's me again!

I have a question about the datamodel design choices. I understand the value of exposing immutable objects to the user, and hiding the concrete implementation behind interfaces: that is standard practice. However, I do not see why it is necessary to have a different Jackson implementation of the data model, for the following reasons:
* There are much simpler ways to let Jackson deserialize immutable objects. Setters are not required at all - either via the use of `@JsonCreator` (which still lets us define `final` fields) or via introspection (which removes the need for a second constructor).
* The current solution involves a lot of deep copying to switch from one implementation to the other, which should have an impact on performance for some applications. One of the goals of WDTK is to process Wikibase dumps, which is a very IO-intense activity, so intuitively this is something we should care about.
* It's very painful to maintain. I have spent tens of hours working on this problem of returning modifying copies of instances, trying to minimize the code duplication in both implementations and the deep copying involved, and I am nowhere near done. I only have a solution for simple top-level modifications, without any unit tests (which will need to be duplicated of course)… This just does not feel right.

Currently I feel like I should be able to:
* first, remove the setters from the jackson implementation;
* second, merge the two implementations altogether;
* third, bury the `DatamodelConverter` and its fellow factories deep down in the git history;
* finally, dance on the graves of all these exterminated Java files.

But I assume you already have dreamed of this plot and might be aware of a reason why it is going to fail. One thing I suspect is that this might be prevented by a mismatch between the structure of the JSON used by Wikibase and the structure of the interfaces used by WDTK. But this is a standard issue and there are many ways to work around it with Jackson.

In any case, I would be grateful if you could show me where the problem lies - I am sure I would stumble upon it myself if I actually tried to do execute my plan, but I happen to have other commitments in life so I would prefer not to have to spend nights on this.

**Comment by wetneb** [comment]
(One last benefit from not using setters in the Jackson implementation: this would provide more meaningful error messages than "insufficiently initialized statement/claim", in issues like #251.)

**Comment by mkroetzsch** [comment]
Hi there! Thanks for the suggestion. I am also not happy with the state of this code. I think simplifying the Jackson implementation does not need any approval: any simplification is good, and we have a lot of tests to check things are not broken.

Merging the two interfaces also seems useful. The one reason why the Jackson code was kept apart from the rest was the concern that Jackson could use a lot of memory due to the more verbose internal structure of the XML, combined with the requirement to store strings for many values (strings require much memory in Java). However, I think this is a minor issue these days, since the large-scale professing of dumps is using Jackson anyway, so that the other, more memory-efficient implementation does rarely get used for large datasets, I suppose.

In short: sounds good to me.

**Comment by Tpt** [comment]
Thank you @mkroetzsch for your input!
I am also in favor of having just one implementation: I agree that most of the DataModel objects are deserialized from JSON or are going to be serialized in JSON so having a second slightly faster / less memory greedy implementation seems to bring more cost than benefits (taking into account that we will have to introduce new structures for #266 and #267).

I would add: on the performance level we probably care more about the deserialization that the serialization (I don't think people build JSON dumps using the WikidataToolkit).
