### ISSUE TITLE
QuantityValue default unit is `"1"` in Wikibase and `""` in WikidataToolkit

### ISSUE THREAD

**Issue by Tpt** [Wikidata/Wikidata-Toolkit#331]
Wikibase uses `"1"` for stating that the value is uniteless (or not set by the user in the UI) and we use `""` as default value in WikidataToolkit. I believe it is quite confusing for the Toolkit users and that we should move to only use one of these representations.

 I believe it would be cleaner to encode both as `"1"`, or maybe even change the unit type to `Optional<String>` or even `Optional<EntityIdValue>` with the `Optional` empty if "1" or "" is given. Move to `Optional` has the (dis)advantage of breaking the code of all people retrieving the unit and, so, make them aware of the change instead of silently introducing this change that may lead to extra bugs if some clients do not care about  `"1"` but only  `""`.

@wetneb  What do you think about it?

**Comment by wetneb** [comment]
`Optional<EntityIdValue>` sounds great - I had some issues in client code because of this being a `String` actually. Preserving backwards compatibility could be done by providing different getters (so that the existing ones would still have the same behaviour).

**Comment by wetneb** [comment]
(or should it be `Optional<ItemIdValue>`?)

**Comment by Tpt** [comment]
+1 for having a different getter and using `Optional<ItemIdValue>`. We should also move the `getGlobe` and `getCalendar `method too. What about  `getUnitId`, `getGlobeId` and  `getCalendarId`? `getGlobeId` and  `getCalendarId` would just return `ItemIdValue`.

We need also to think about what should be done if the unit/globe/calendar URI is invalid. I see 3 options:
1. Return `Optional.empty` but we would not be able to encode the uniteless case and it makes the return type heavier for `getGlobeId` and  `getCalendarId`.
2. Raise an exception when the getter is called. I believe that we should not raise an exception during the deserialization in order to don't make the processing of Wikidata dumps that contains some invalid URIs fail.
3. Encode bad URIs using a special implementation of ItemIdValue that would raise an exception when `getId` or `getSiteIri` is called but return the URI when `getIri` is called. It is quite dangerous for code calling the method but it would still allow us to represent all possible values (and so deprecate `getUnit`, `getGlobe` and `getCalendar`).

**Comment by wetneb** [comment]
Migrating globe and calendar isn't a huge priority for me (compared to unit) but sure, that would be more consistent. It looks like option 2 would be the cleanest AFAICT.

**Comment by Tpt** [comment]
> It looks like option 2 would be the cleanest AFAICT.
When we take the point of view of the new getters, definitely. But it means we still need to keep the current getters in order to make the invalid units/... still accessible (e.g. if we want to write a bot to fix them).

**Comment by Tpt** [comment]
Done in release 0.9.0
