### ISSUE TITLE
Some properties do not show up in list of properties

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Wikidata/Wikidata-Toolkit#363]
e.g. https://tools.wmflabs.org/sqid/#/browse?type=properties
does not show https://www.wikidata.org/wiki/Property:P698 (PMID)

**Comment by Tpt** [comment]
I believe that this problem should be tracked in [SQID](https://github.com/Wikidata/SQID) instead of here because the Wikidata-Toolkit bug trackers focuses on the library feature and not its usage by SQID.

**Comment by Daniel-Mietchen** [comment]
SQID's footer links here, so I thought stuff should be posted here. Just opened a ticket over there.
