### ISSUE TITLE
Invalid deserialization of editing results on properties

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#376]
Editing a property with `wbeditentity` returns the JSON payload for the entity, but without the datatype. That's a bit funny but I assume the reason is that the datatype cannot be changed anyway.
So, deserialization of the response as a `PropertyDocument` fails.

**Comment by wangchuan2008888** [comment]
I solve this by modify `wikibase` code. Maybe add another query for created property also works,

**Comment by jjkoehorst** [comment]
@wetneb is there any solution except try catch and parse the message? 

```
Cannot construct instance of `org.wikidata.wdtk.datamodel.implementation.PropertyDocumentImpl`, problem: `java.lang.NullPointerException`
 at [Source: UNKNOWN; line: -1, column: -1]
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.wikidata.wdtk.datamodel.implementation.PropertyDocumentImpl`, problem: `java.lang.NullPointerException`
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
```

**Comment by wetneb** [comment]
we should just fix this in WDTK itself, really! I would solve this by introducing a new class which represents a property without its datatype, use this to deserialize the editing action result, and then return this to the user or return a full property if the datatype is known from elsewhere (previous version of the property).

**Comment by Tpt** [comment]
This bug [will be fixed in Wikibase](https://lists.wikimedia.org/pipermail/wikidata-tech/2021-February/001588.html) in a few days.

**Comment by robertvazan** [comment]
#570 resolves this by returning `void` from `WikibaseDataEditor.editEntityDocument()`. See [reasoning](https://github.com/Wikidata/Wikidata-Toolkit/issues/403#issuecomment-812869885) behind this design.
