### ISSUE TITLE
WikibaseDataFetcher does not expose IOException

### ISSUE THREAD

**Issue by marco-schmidt** [Wikidata/Wikidata-Toolkit#421]
I'm using WD-TK 0.10.0's WikibaseDataFetcher class to run a query with method searchEntities: https://github.com/marco-schmidt/am/blob/5e5ec61a3e6b5937235877f7b1e38b175fd1eab9/src/main/java/am/validators/MovieValidator.java#L199
I catch MediaWikiApiErrorException and would have expected to be told by that exception if networking issues occur, but this is not the case.

Debugging the class I figured out that it uses WbSearchEntitiesAction internally. As a result of issues #402 and #404 the API already exposes IOException, but these extensions have not made it into WikibaseDataFetcher. Is this on purpose? Should I mirror the internal usage of WbSearchEntitiesAction instead? I like WikibaseDataFetcher and would rather try to avoid replicating code that involves parsing JSON results, but I need to distinguish between "no results" and "having problems getting results".

As a sidenote, I'd like to be able to
- access the URI used and 
- actively close a fetcher's connection. But am I correct that both are unavailable from the outside when using the fetcher class defaults?

Thanks for your library and any feedback,
Marco

**Comment by wetneb** [comment]
We have made similar changes in the editing classes recently, so I would trust your judgment and adapt how exceptions are handled in these methods. The need to distinguish between "no results" and "having problems getting results" seems to be a pretty basic one. Feel free to draft a PR so we can discuss the concrete changes more easily :)
