### ISSUE TITLE
Support for unknown datavalues

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#422]
Support for new datatypes is regularly added to Wikidata.

Every time this happens, previous versions of WDTK will be unable to deserialize EntityDocuments where these datatypes are used. This means that code written using WDTK will choke on these entities, even if the particular task at hand does not do anything with these statements with unknown datatypes. This seems less than ideal to me.

In principle, WDTK should be able to deserialize datavalues with unknown datatypes by just by recording their JSON representation, so that these values can be serialized back in the same format. The Java representation of these datavalues would be opaque to the user - they would not be able to manipulate them in any useful way. So as a user these datatypes would of course still be "unsupported" but their presence in an EntityDocument would not prevent you from doing work that does not interact with the values.

That design should work fine for items, but it would still choke on `PropertyDocument`s with unknown datatypes. That is less of a concern as far as I can tell, but ideally it would be nice to handle this case as well.

@Tpt any thoughts?

**Comment by wetneb** [comment]
Actually `DatatypeIdImpl` seems to handle unknown datatypes gracefully at the moment, so it is just a matter of adding a new `ValueImpl` subclass, with the appropriate visibility.

**Comment by wetneb** [comment]
The datatypes recently introduced by WMDE are:
- lexeme, forms and senses -> these are new entity ids, causing issues mentioned in #407 on old versions of WDTK
- musical notation, mathematical formula, and other similar datatypes, which use strings as underlying datavalue -> WDTK did not choke on these.

However, I think it would be useful to have a fallback for all possible datatypes, not just for new entity ids of new types.

**Comment by Tpt** [comment]
I believe we need to keep in mind the distinction that Wikibase does between datavalues and datatypes.

1. DataValues are the data structures. Currently the ones used by Wikidata are "string", "monolingual-text", "wikibase-entityid", "time", "globe-coordinates" and "quantity". They are presented in WikidataToolkit by a sub interface of `Value` and WikidataToolkit hard fails on unknown datavalues.

2. DataTypes that are a "type" "tag" stored in the property descriptions and returned as part of the snak serialization by some Wikibase API/dumps. For example, "wikibase-item", "wikibase-property"... are possible datatypes for the "wikibase-entityid" data value type, "commons-media" or "external-id" for "string"... They are presented by the `DatatypeId` interface and WikidataToolkit should not break if a new datatype is introduced.

There is one exception to this scheme in WikidataToolkit: each entity id (property id...) are encoded in a different implementation `ItemIdImpl`... leading to the hard fail on lexeme ids with the old versions of WikidataToolkit.

I agree that we should introduce an `UnknownValue` structure to represent the dataValues of unknown type. Its implementation would store the JSON representation as an opaque blob. It should probably not be allowed to instantiate it outside of the JSON deserialization process.
A `UnknownEntityId` extending `EntityId` is probably also required for new entity ids.

What do you think about it?

**Comment by wetneb** [comment]
Yeah, exactly. For entity ids, we can either use the generic fallback (which would not implement `EntityIdValue`) or have a second fallback class which would implement `EntityIdValue`. No strong feelings about either case, but for the second I guess we would need to assume that all entities introduced in the future will always have an `"id"` field in their JSON representation, so that we can implement `String getId()` there. Or we can throw some exception too.

**Comment by Tpt** [comment]
>  I guess we would need to assume that all entities introduced in the future will always have an "id" field in their JSON representation

This assumption is actually enforced on Wikibase side with the fact that they are all using the "wikibase-entityid" DataValue type. So, I believe it is safe to assume it too.

**Comment by thadguidry** [comment]
Ah! that enforcement I was not aware of either TPT... are you absolutely
sure about that however?

Thad
https://www.linkedin.com/in/thadguidry/
