### ISSUE TITLE
Upgrade password-based login to use appropriate API action

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#426]
When logging in we currently get warning messages indicating that we are not using the API as we should:
```
[main] WARN org.wikidata.wdtk.wikibaseapi.ApiConnection - API warning [main]: Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application.
[main] WARN org.wikidata.wdtk.wikibaseapi.ApiConnection - API warning [login]: Main-account login via "action=login" is deprecated and may stop working without warning. To continue login with "action=login", see [[Special:BotPasswords]]. To safely continue using main-account login, see "action=clientlogin".
```

I believe this could be linked to issues with old passwords considered too short by the current standards:
https://www.wikidata.org/wiki/Wikidata_talk:Tools/OpenRefine#Invalid_credentials

This is probably also required for 2FA login #412.

**Comment by robertvazan** [comment]
The old login method shouldn't be deprecated though. I do use the BotPasswords method. There should be two login methods, one for full user login and one for restricted access via BotPasswords.

**Comment by Lhaaits** [comment]
I would like to build in the clientLogin action. I have it working in Postman so I know which steps and parameters are needed. Is there anything against implementing it?

**Comment by wetneb** [comment]
I think it would be very welcome indeed!

**Comment by Lhaaits** [comment]
I made a pull request: https://github.com/Wikidata/Wikidata-Toolkit/pull/707. I wasn't able to run `mvn clean install` locally though, because I need some gpg key:
```
[INFO] --- maven-gpg-plugin:3.0.1:sign (sign-artifacts) @ wdtk-parent ---
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

**Comment by wetneb** [comment]
You can actually use any GPG key for that: you just need to register it in your personal Maven config.

**Comment by thadguidry** [comment]
> 

@Lhaaits would you mind adding that info "any GPG key" to our technical contributor docs to help others in the future? Thanks!

**Comment by Lhaaits** [comment]
@thadguidry where can I find the technical contributor docs?

**Comment by wetneb** [comment]
I suspect @thadguidry might have mixed up this project and OpenRefine

**Comment by thadguidry** [comment]
Oops yes sorry was on mobile

**Comment by Lhaaits** [comment]
> I made a pull request: #707. I wasn't able to run `mvn clean install` locally though, because I need some gpg key:
> 
> ```
> [INFO] --- maven-gpg-plugin:3.0.1:sign (sign-artifacts) @ wdtk-parent ---
> gpg: no default secret key: No secret key
> gpg: signing failed: No secret key
> ```

It's working locally now. I created a gpg key and added the passphrase to my ~/.m2/settings.xml. @wetneb could you have a look at the PR when you have time?
