### ISSUE TITLE
performance issue?

### ISSUE THREAD

**Issue by luisenriqueramos1977** [Wikidata/Wikidata-Toolkit#446]
Dear friends, 

I am currently working in a private wikidata instance. Finally we began to upload our items there, however when loading I am doing it at a rate of 100 items per minute. Giving that we have to edit 1.500.000 items, that means we would require 30 working days to load all this information, then naturally I wonder if this should be a normal upload rate?, or if there were another way to improve it?. 

I tested my application loading first an item with an statement, progressively until having one item with all statements, and the time result was the same for every case. 

our administrator indicated me that according to this site:

https://www.mediawiki.org/wiki/Manual:$wgRateLimits, the default edits are limited to     'user' => [ 90, 60 ], 90 edits every 60 seconds. 

is it possible to change that from this  api?

Luis Ramos

**Comment by wetneb** [comment]
I don't think you can change these limits via the API, they are set in the configuration of your Wikibase instance.

**Comment by robertvazan** [comment]
Why is this open? Is there anything to do on WDTK level?

**Comment by luisenriqueramos1977** [comment]
well, I open the issue and to now I do not know if there is a solution. 
about your question:
Is there anything to do on WDTK level?, I wonder the same, and hope we could do something from WDTK site.

Luis

**Comment by wetneb** [comment]
So, the solution is to change `wgRateLimits` in the configuration of your Wikibase instance. There is no way to do this via the API and therefore it is impossible to add support for this in WDTK.
