### ISSUE TITLE
Make statements always have valid ids

### ISSUE THREAD

**Issue by Tpt** [Wikidata/Wikidata-Toolkit#447]
Currently `Statement`s are allowed to use the `""` statement id to tag the statement as new. Then, when editing, the `wikibaseapi` module is generating a new valid id and, if a conversion to RDF happens, the RDF converter should do the same.

It might make sense to make the `Statement` constructors to generate a new valid id if no id is provided.

@wetneb Do you think it make sense? Would it create problems on the API wrapper side to distinguish new statements from edited ones?

Related issue:  #166

**Comment by wetneb** [comment]
There are a few things to watch out for I think. Here are two (not pretending this is exhaustive):

* If you allocate a new id in the `Statement` constructor, then you need to call a random number generator there, so the same generator call will not generate equal statements. This breaks the determinism of the data model implementation which might have unforeseen consequences at various places in the code. It is also harder to mock this random generation in tests.

* Yes, as you point out, there could be issues with not being able to reproduce the semantics of the current empty ID field to represent new statements.

But perhaps none of these are actually blocking and the change is doable. I'll keep thinking about it.

**Comment by robertvazan** [comment]
@Tpt Can this be closed with conclusion that there are valid use cases for empty statement ID?

**Comment by Tpt** [comment]
Yes, indeed.
