### ISSUE TITLE
enums with this API

### ISSUE THREAD

**Issue by luisenriqueramos1977** [Wikidata/Wikidata-Toolkit#466]
Dear Wikidata developers, 

I wonder if it would be possible to create enums within his API?, I mean I would to create a property, and have the possibility to select from a list of values, that I have set up previously. 

for instance:

status {active, inactive}
And that the user could choose between those string values. 

Luis Ramos

**Comment by wetneb** [comment]
Hi @luisenriqueramos1977,

Yes that is typically something you could do. That sort of functionality would probably live outside of Wikidata-Toolkit if I understand your request correctly. You should be able to write such code yourself using the API we provide.

**Comment by luisenriqueramos1977** [comment]
Okay, thanks for your quick answer!

I will try, if no succeed, I will contact you again. 


Luis Ramos
