### ISSUE TITLE
qualified period of time

### ISSUE THREAD

**Issue by luisenriqueramos1977** [Wikidata/Wikidata-Toolkit#468]
Dear colleges, 

I am trying to create some set of time periods properties values as follows:

ITEM

time_periods    time_period
                                 start_period    some date1
                                 end_period     some date2
                                period type      atype
                        time_period
                                start_period    some date3
                                 end_period     some date4
                                period type     anothertype

where time_period is a list of size "n" and it is repeated every time there is a new start_period and end period. 

I have tried to represent start_period, end_period and period type as snaks, but when I try to integrate them, system says snakgroups must be of same property, so I can not make a snakgroup with start_period, end period, and period type, then I wonder what method is recommended to generate this output?. 

I need to create a set to integrate start_period, end_period, and period type and then assign them to time period, in a list or map, and at the end assign all the periods to time_periods.

I attached an image with the output edition done by hand. 

Thanks in advanced for any recommendation

Luis Ramos

[relationshipperiods.pdf](https://github.com/Wikidata/Wikidata-Toolkit/files/3950662/relationshipperiods.pdf)

**Comment by wetneb** [comment]
> I have tried to represent start_period, end_period and period type as snaks, but when I try to integrate them, system says snakgroups must be of same property, so I can not make a snakgroup with start_period, end period, and period type, then I wonder what method is recommended to generate this output?

You should group all the qualifiers of a given statement by property, and then create a snak group for each of those groups. In many cases, this means essentially having one snak group for each qualifier (since qualifiers often use different properties).
