### ISSUE TITLE
Question : how to rollback all updates made with wikidata-toolkit ? (bot development)

### ISSUE THREAD

**Issue by tfrancart** [Wikidata/Wikidata-Toolkit#481]
Hello

In the context of ISSN project, described at https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_Periodicals#Data_donation_from_ISSN_Register_-_Feedback_welcome, we are considering to use Wikidata Toolkit to modify wikidata. An important question for us is : do we have the ability to rollback a transaction of updates using Wikidata Toolkit ? is it related to "editAsBot" flag ? and what are the consequences on the script we will develop ? does it require to have a specific Wikidata account ?

I am unfamiliar with how to develop bots for Wikidata...

Thanks

**Comment by wetneb** [comment]
Sadly that's not supported by MediaWiki natively, nor have we got dedicated support for this in WDTK.

However, there is an EditGroups tool which can help you with that:
https://www.wikidata.org/wiki/Wikidata:Edit_groups
https://tools.wmflabs.org/editgroups/

In short: all you need to do is to add a hash to your edit summaries, following a particular format, as described here:
https://www.wikidata.org/wiki/Wikidata:Edit_groups/Adding_a_tool

**Comment by tfrancart** [comment]
Thanks for the pointers ! that's what I am looking for.
I'll close this issue.
