### ISSUE TITLE
Conversion from Commons file names to Mid

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#487]
To make it easier to use WDTK to add structured data to files on Wikimedia Commons, it could be useful to include a utility to convert file names to entity identifiers.

This can be done by batches of file names using the MediaWiki API:
https://commons.wikimedia.org/w/api.php?action=query&titles=File:Albert%20Einstein%20Head.jpg|File:Cat.jpg&format=json

```
{
    "batchcomplete": "",
    "query": {
        "pages": {
            "925243": {
                "pageid": 925243,
                "ns": 6,
                "title": "File:Albert Einstein Head.jpg"
            },
            "32455073": {
                "pageid": 32455073,
                "ns": 6,
                "title": "File:Cat.jpg"
            }
        }
    }
}
```
This means that `File:Albert Einstein Head.jpg` translates to entity id `M925243`, and `File:Cat.jpg` translates to `M32455073`. A reverse translation could also be provided by WDTK.

The Minefield tool does this translation:
https://github.com/hay/wiki-tools/blob/master/public_html/minefield/js/app.js

It is not clear whether we would use this feature in OpenRefine itself, as the conversion could be handled by a reconciliation service instead (but then WDTK could be used to build the reconciliation service!).

**Comment by Tpt** [comment]
`WikibaseDataFetcher.getEntityDocumentsByTitle("commonswiki", "File:Albert Einstein Head.jpg", "File:Cat.jpg")` is already possible with WDTK. An empty `MediaInfoDocument` is returned for the files for which the MediaInfo entity does not exist yet.

**Comment by afkbrb** [comment]
Hi, can I work on this?

**Comment by afkbrb** [comment]
How about creating a new util class  `WmCommonsUtils` at the api module? Because `WikibaseDataFetcher`  mainly gets results for entities, but here we only need pageId and title. Also, if we implement the corresponding functions in `WikibaseDataFetcher` , we'll need to make sure that the apiBaseUrl of the fetcher instance is "https://commons.wikimedia.org/w/api.php".

I'm thinking about exposing the follwing api in  `WmCommonsUtils`:
```java
public static String getPageIdByFilename(String filename) {

}

public static String getFilenameByPageId(String pageId) {

}

```

Looking forward to your suggestions.

**Comment by Tpt** [comment]
@afkbrb Hi! Thank you for your help!

Indeed. The API methods you suggest are not be much related to entities, so having an other class for that seems meaningful.
It is possible to fetch the page id for any page title (like "File:Foo.jpg" or "Main_page"...) so I would do more general methods like `getPageIdForTitle` and `getTitleForPageId`. This API would not be restricted to WMCommons.

An other option would be to provide an higher level API, directly returning a `MediaInfoId` for a file name with something like `getMediaIdForFileName`. In any case we would probably like to be able to fetch multiple ids for multiple titles just like it is currently possible with entities.

**Comment by wetneb** [comment]
> In any case we would probably like to be able to fetch multiple ids for multiple titles just like it is currently possible with entities.

Yes, that sounds like a pretty important need.

**Comment by afkbrb** [comment]
> How about creating a new util class WmCommonsUtils at the api module?

Changed my mind. As @Tpt said, this API shoud not be restricted to WMCommons, so creating the `WmCommonsUtils ` class is inappropriate. We should still create the new methods in `WikibaseDataFetcher `.  

We now have `getEntityDocumentsByTitle` in `WikibaseDataFetcher `, so creating a new method `getMediaInfoIdsByTitle` there seems logical. A more significant benefit is that we can use the instance variable `connection` to support different api endpoints.

So the new proposal is that we create the following methods in `WikibaseDataFetcher `:

```java
MediaInfoIdValue getMediaInfoIdByTitle(String title)

Map<String, MediaInfoIdValue> getMediaInfoIdsByTitle(String... titles)

Map<String, MediaInfoIdValue> getMediaInfoIdsByTitle(List<String> titles)
```

By doing this, we can reuse lots of code from `getEntityDocumentsByTitle` and its variants. And it's also a good way to support fetching multiple ids for multiple titles within a request.

**Comment by wetneb** [comment]
Sounds great to me!

This is a fairly high-level interface in the sense that it is really specific to the way MediaInfo entities are constructed on Commons. But I am not aware of any other Wikibase also constructing entity ids in the same way, so I would say it makes sense to keep it in this form for now - it should not be hard to decompose this into more low-level methods later on, if the need arises…
