### ISSUE TITLE
Rewrite JsonConverter tests

### ISSUE THREAD

**Issue by fer-rum** [Wikidata/Wikidata-Toolkit#49]
The current tests are not satisfying enough and highly redundant. Smaller, more precise tests are needed.

Also @eldur pointed out, that one could use *fasterxml.jackson* for this purpose. This issue is for discussing this aspect also.

**Comment by fer-rum** [comment]
Are we satisfied with the current test coverage or does this still need improvement?

**Comment by mkroetzsch** [comment]
Closing this old bug. Tests have been rewritten when introducing Jackson, and I don't see a huge need for specifically extending the tests for JSON-related code right now.
