### ISSUE TITLE
Wikidata login started failing over the past few days

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#491]
The following test (with valid Wikidata username and passwords) currently fails:

```java
    @Test
    public void testLogin() throws LoginFailedException {
        ApiConnection connection = ApiConnection.getWikidataApiConnection();
        connection.login("username", "password");
    }
```

This prevents all OpenRefine users from logging in via the tool: https://github.com/OpenRefine/OpenRefine/issues/2526

**Comment by wetneb** [comment]
Phabricator task about the incident: https://phabricator.wikimedia.org/T249680

**Comment by Tpt** [comment]
I just released a new version with this bug fixed.
