### ISSUE TITLE
Migrate to a high level HTTP library to query the MediaWiki API

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#492]
We are currently using `HTTPUrlConnection` to issue HTTP requests to the MediaWiki API, at various places in the code. We should use a higher-level library which would handle variations in the responses more reliably. For instance, OkHTTP is a popular one.

The use of this low-level interface has caused serious bugs: #491, #271.

Upgrading to a high-level interface would potentially solve other issues, such as #151.

Since we are considering introducing ScribeJava as a dependency in #411, one could check if that already depends on a high-level HTTP library.

**Comment by wetneb** [comment]
Apparently our `wdtk-wikibaseapi` module already depends on `org.apache.httpcomponents:httpclient` wIthout actually using it (as `mvn dependency:analyze` confirms). So that is one candidate.

scribejava-core, that #411 introduces as a dependency, does not itself depend on any HTTP library.
To use scribejava-apis, which is likely to get pulled in as well, one needs to pull in one of the following HTTP backends:
* OkHTTP
* Apache HTTP Components (that we already depend on)
* HttpURLConnection, that we want to migrate out of;
* a bunch of async ones, which look less relevant for this project.

So I'd say OkHTTP and Apache HTTP Components are two good candidates for this.
OkHTTP seems to be more actively maintained, supports HTTP/2, and seems to offer a more high-level API, so I would go for that.

**Comment by afkbrb** [comment]
OkHTTP was imported in #411 , I'll take this and migrate BasicApiConnection to use OkHTTP.
