### ISSUE TITLE
Version 0.11.1 of wdtk-testing is not published on Maven Central

### ISSUE THREAD

**Issue by floscher** [Wikidata/Wikidata-Toolkit#495]
The artifact `wdtk-testing` is [not published to Maven Central](https://search.maven.org/artifact/org.wikidata.wdtk/wdtk-testing).

This leads to build failures when e.g. depending on [org.wikidata.wdtk:wdtk-wikibaseapi:0.11.1](https://search.maven.org/artifact/org.wikidata.wdtk/wdtk-wikibaseapi/0.11.1/jar), because that artifact depends on the missing one.

**Comment by wetneb** [comment]
This must have been some sort of glitch in the upload process. Since many other versions have been published since, I think we can close this.
