### ISSUE TITLE
Where to place additional files for JavaDoc

### ISSUE THREAD

**Issue by fer-rum** [Wikidata/Wikidata-Toolkit#50]
Additional documentation files like images are to be handled like desctibed [here](http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#sourcefiles).

**Miscellaneous Unprocessed Files**

You can also include in your source any miscellaneous files that you want the Javadoc tool to copy to the destination directory. These typically includes graphic files, example Java source (.java) and class (.class) files, and self-standing HTML files whose content would overwhelm the documentation comment of a normal Java source file.

To include unprocessed files, put them in a directory called _doc-files_ which can be a subdirectory of any package directory that contains source files. You can have one such subdirectory for each package. You might include images, example code, source files, .class files, applets and HTML files. For example, if you want to include the image of a button button.gif in the java.awt.Button class documentation, you place that file in the /home/user/src/java/awt/doc-files/ directory. Notice the doc-files directory should not be located at /home/user/src/java/doc-files because java is not a package -- that is, it does not directly contain any source files.

All links to these unprocessed files must be hard-coded, because the Javadoc tool does not look at the files -- it simply copies the directory and all its contents to the destination. For example, the link in the Button.java doc comment might look like:

``` Java
    /**
     * This button looks like this: 
     * <img src="doc-files/Button.gif">
     */
```

**Comment by robertvazan** [comment]
@Tpt @wetneb This should be probably closed.
