### ISSUE TITLE
Adding afkbrb as project member

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#505]
I propose we add @afkbrb to the project as a member.

Lu is an OpenRefine GSoC student who works on OAuth support in OpenRefine (and therefore in WDTK) and Wikibase support in OpenRefine too. He has made multiple PRs to this repository, which are all of a very high standard in my opinion.

Being a project member will let him work on PRs opened by others (such as #411) more easily, add tags to issues, and other things like that.

If there is no opposition to this, I can add him.

**Comment by Tpt** [comment]
It's a great idea! Thank you for your contributions @afkbrb!

**Comment by afkbrb** [comment]
Thanks @wetneb @Tpt , it's my honor to join this organization.

**Comment by wetneb** [comment]
Done!
