### ISSUE TITLE
updateStatements vs. editItemDocument

### ISSUE THREAD

**Issue by tfrancart** [Wikidata/Wikidata-Toolkit#508]
(Related to https://www.wikidata.org/w/index.php?title=Wikidata_talk:WikiProject_Periodicals#Data_donation_from_ISSN_Register_(Followup))

When editing an item, we would like to add labels or aliases so I am considering using `editItemDocument()` instead of `updateStatements()`.

In the case I need to update a Statement, to add references or to add qualifier or to adjust the value (e.g. set a different language on a MonolingualTextValue), should I:
1. Try to update the existing Statement object on the ItemDocument obtained through WikibaseDataFetcher ?
2. Or use StatementBuilder to recreate an identical Statement, give it the existing statement ID,  modify whatever I need to modify on it, and add this new Statement to the ItemDocument ? will it be merged properly with the existing one ?

(Note : in the examples, EditOnlineDataExamples illustrates only `updateStatements()` and not `editItemDocument()`, this could be a useful addition)

Thanks !

**Comment by wetneb** [comment]
Yes you should create a copy of the initial statement, with the same statement id. If you are using `editItemDocument` then you should create a copy of the `ItemDocument` where the original statement has been replaced by the new one. But it is simpler to use `updateTermsStatements` which takes care of the merging for you.

**Comment by tfrancart** [comment]
Thanks for pointing me to `updateTermsStatements` which I overlooked !
I think I will use that.
