### ISSUE TITLE
Support for language code "mul" (multilingual) ?

### ISSUE THREAD

**Issue by tfrancart** [Wikidata/Wikidata-Toolkit#509]
That page https://www.wikidata.org/wiki/Help:Monolingual_text_languages, as well as the list of supported languages at https://www.wikidata.org/wiki/Help:Wikimedia_language_codes/lists/all clearly state that `mul` is a valid language code to state that a value is multilingual.

However when I try to send a MonolingualTextValue with `mul` as a language code, I get an error stating the language code is not recognized. Below the error, with the statementsToAdd printed (see the "mul" language code)

```
15:20:44.295 DEBUG o.i.i.IssnBot - Added Statements [[ID ] http://www.wikidata.org/entity/Q84025820 (item): http://www.wikidata.org/entity/P1476 :: "Medicina subacquea e iperbarica" (mul)
  Reference:
      http://www.wikidata.org/entity/P248 :: http://www.wikidata.org/entity/Q70460099 (item)
      http://www.wikidata.org/entity/P236 :: "2037-1136"
, [ID ] http://www.wikidata.org/entity/Q84025820 (item): http://www.wikidata.org/entity/P407 :: http://www.wikidata.org/entity/Q20923490 (item)
  Reference:
      http://www.wikidata.org/entity/P248 :: http://www.wikidata.org/entity/Q70460099 (item)
      http://www.wikidata.org/entity/P236 :: "2037-1136"
]...
15:20:45.018 ERROR o.i.i.IssnBot - [not-recognized-language] The supplied language code was not recognized.
org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [not-recognized-language] The supplied language code was not recognized.
	at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:68)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:524)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:464)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:747)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:308)
	at org.wikidata.wdtk.wikibaseapi.TermStatementUpdate.performEdit(TermStatementUpdate.java:454)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateTermsStatements(WikibaseDataEditor.java:738)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateTermsStatements(WikibaseDataEditor.java:578)
	at org.issn.issnbot.IssnBot.processSerial(IssnBot.java:290)
	at org.issn.issnbot.IssnBot.main(IssnBot.java:437)
```

I see that "multilingual" at https://www.wikidata.org/wiki/Q20923490 has a bunch of issues because it is a _subclass of_ Languoid and not an _instance of_ Languoid. Could that be related ?

**Comment by wetneb** [comment]
Looking at the trace, it seems that the error is thrown not by Wikidata-Toolkit itself, but rather by the Wikibase instance. Are you editing Wikidata or another Wikibase instance?

Note that there is a difference between language codes allowed for terms (labels, descriptions and aliases) and those allowed for monolingual text values in statements. And I suspect there are Wikimedia language codes which are not allowed in any of those locations (they might be useful somewhere else in Wikimedia projects) - perhaps `mul` is one of these?

Can you add this language code manually via Wikidata's UI by the way?

**Comment by tfrancart** [comment]
> Looking at the trace, it seems that the error is thrown not by Wikidata-Toolkit itself, but rather by the Wikibase instance. Are you editing Wikidata or another Wikibase instance?

Wikidata

> Can you add this language code manually via Wikidata's UI by the way?

Oups, no !

I went ahead and made "multilingual" at https://www.wikidata.org/wiki/Q20923490 instance of languoide, let's see.

**Comment by tfrancart** [comment]
As listed here https://www.wikidata.org/wiki/Wikidata:Database_reports/monolingual_text/multiple_languages a bunch of items do have labels with language code "mul" but strangely enough I cannot use it as a language code when entering a value.

**Comment by tfrancart** [comment]
Solved on the mailing list : https://lists.wikimedia.org/pipermail/wikidata/2020-June/014105.html
