### ISSUE TITLE
Migration out of Travis

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#515]
Since Travis introduced a new pricing model we might need to consider moving to a different CI platform. Options?
- Migrating the repository to GitLab to use GitLab CI
- Using GitHub Actions
- Using CircleCI
- Other free CI providers for OSS?

**Comment by Tpt** [comment]
Great point. If we stay on GitHub, GitHub Actions has the advantage of being integrated into the platform and easy to setup. I use it for quite a lot of repositories and I am happy with it. So it seems to me that it is the best short term choice.
