### ISSUE TITLE
How does wbsearchentities select entities? 

### ISSUE THREAD

**Issue by hideodeo** [Wikidata/Wikidata-Toolkit#521]
I am not sure if this repo is an appropriate place to ask this, but I am wondering how wbsearchentities selects & orders entities given a text as an input.

It seems this page is not explaining how it works.
https://www.wikidata.org/w/api.php?action=help&modules=wbsearchentities

**Comment by wetneb** [comment]
I would also be interested in reading documentation about this! But you are correct that this is not the right place to ask for it, that is done by Wikibase itself.
I think you could file a phabricator ticket about this at https://phabricator.wikimedia.org/.
