### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by robertvazan** [Wikidata/Wikidata-Toolkit#527]
Eclipse reports 56 warnings in WDTK. I can see several categories:

* abuse of `JsonMappingException` for application exceptions
* unused imports
* testing of deprecated APIs
* using deprecated WDTK APIs in WDTK itself
* some changes in recent okhttp3, commons-io
* missing `serialVersionUID`
* unused fields
* probably incomplete tests (unused methods in `RdfConverterTest`)

Would you mind me submitting a PR that fixes most of them? I would also suppress warnings on tests that check deprecated APIs.

The only thing I am not sure about is what to do with unused methods in `RdfConverterTest` (`createTestPropertyDocument` and `createWrongTestPropertyDocument`). Delete them?

**Comment by Tpt** [comment]
Yes, please. 

> The only thing I am not sure about is what to do with unused methods in RdfConverterTest (createTestPropertyDocument and createWrongTestPropertyDocument). Delete them?
Yes!

**Comment by wetneb** [comment]
Closed by #533.
