### ISSUE TITLE
Serializing model object

### ISSUE THREAD

**Issue by msx80** [Wikidata/Wikidata-Toolkit#532]
Hi there, i was trying to serialize an ItemDocumentImpl to implement a simple cache, but it looks like it's not serializeable.

`Caused by: java.io.NotSerializableException: org.wikidata.wdtk.datamodel.implementation.ItemDocumentImpl
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)`

I've seen from issue #74 and pull request #110 that the default model should be Serializable. Maybe it was reverted for some reason?

**Comment by wetneb** [comment]
I think this has been dropped later on indeed, I am not sure why. I think it could be worth reintroducing it, I can see it being useful in many contexts.

In the meantime, if this is an option for you, you could potentially serialize it to JSON, either with the utilities in WDTK or directly with Jackson.

**Comment by msx80** [comment]
> you could potentially serialize it to JSON, either with the utilities in WDTK

Would you mind pointing me at these utilities? I can see stuff being unserialized in WbGetEntitiesAction.wbGetEntities() but it's not immediately reusable.

In addition to Serializable, you could consider giving data model objects a no-args constructor to make them play well with other serializers, like Kryo, that requires it. I can see that this is much more work and a much narrower problem so feel free to ignore :)

**Comment by wetneb** [comment]
> Would you mind pointing me at these utilities? I can see stuff being unserialized in WbGetEntitiesAction.wbGetEntities() but it's not immediately reusable.

We have this: http://wikidata.github.io/Wikidata-Toolkit/org/wikidata/wdtk/datamodel/helpers/JsonSerializer.html
But it will not let you serialize all classes of the datamodel, only the EntityDocuments.

> In addition to Serializable, you could consider giving data model objects a no-args constructor to make them play well with other serializers, like Kryo, that requires it. I can see that this is much more work and a much narrower problem so feel free to ignore :)

I think that would go against the goal to keep all these datamodel classes immutable. I am not so familiar with Kryo so I don't know if there is a way to make it work in that case?

**Comment by wetneb** [comment]
Closing since the JsonSerializer should be enough for that case.
