### ISSUE TITLE
Take part in Abstract Wikipedia licensing discussion

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/Wikidata-Toolkit#636]
Abstract Wikipedia is currently debating the license terms under which code should be published there. Mostly, it seems to turn into a GPL vs Apache debate (or restrictive vs. permissive open source). This seems to be relevant to Wikidata toolkit, since:
- Abstract Wikipedia is supposed to (among other things) publish code that can be used to verbalise data, and which could be useful for the project at some point
- Wikidata Toolkit is Apache licensed, so would not be compatible with GPLed code (as far as I understand)

It might therefore be good for the developers of this project to contribute to the discussion while final decisions are still not made:

https://meta.wikimedia.org/wiki/Talk:Abstract_Wikipedia/Licensing_discussion

(I already did that, but not mainly to represent the project, which I am no longer the maintainer of, and in any case, I understand that the Wikimedia decision process is based on personal views rather than on projects or organisations speaking up as a whole.)

**Comment by wetneb** [comment]
Thanks for the heads up! The discussion is now closed, so I am closing this ticket too.
