### ISSUE TITLE
Support for file uploads

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#638]
WDTK supports creating new items, properties and lexemes, but not MediaInfo entities, and for a good reason: those cannot be created without uploading the corresponding file (to Commons at least).

Would it be appropriate to add support for file upload, via [the corresponding MediaWiki API action](https://commons.wikimedia.org/w/api.php?action=help&modules=upload)? That API action has nothing to do with Wikibase itself, so I could understand that it is considered out of scope, but at the same time it does feel like we should be able to reuse an `ApiConnection` from WDTK to also perform this action.

More generally, we could potentially think about how to make it easier to reuse an `ApiConnection` object for MediaWiki API actions which are not directly supported by WDTK. Intuitively, it can make sense to use most of the MediaWiki API actions within the context of Wikibase, and there is no chance we implement a wrapper for every single of those actions in WDTK any time soon, right? Perhaps the right way to phrase this would be to look for MediaWiki Java clients and see if there could be some sort of interoperability.

**Comment by wetneb** [comment]
@Tpt curious what you think about this! :)

**Comment by Tpt** [comment]
It's a great question! I would say explicitly proviidng code for uploading file is out of scope of Wikibase but we definitely should provide some ways to make it easy to do action API calls not explicitly supported by WDTK using the `ApiConnection` object. Interop with existing Java client(s) would be even better indeed. We should also keep in mind the there is a work in progress REST API for Wikibase and we might want to migrate WDTK to it, maybe dropping the action API support in the process.

**Comment by wetneb** [comment]
Let's close this then, we will try to do upload actions on our own (accessing the credentials from Wikidata-Toolkit in some way, for instance by abusing JSON serialization)

**Comment by wetneb** [comment]
I looked into this and it seems that we are nearly there: `ApiConnection` already provides public methods to perform arbitrary API actions. The only missing piece is the ability to pass files in those requests, so I would propose to add that.
