### ISSUE TITLE
Duplicated statements with the editor.editEntityDocument api

### ISSUE THREAD

**Issue by j-sal** [Wikidata/Wikidata-Toolkit#645]
When using the new `editor.editEntityDocument` api, Alias (for existing Items) and Label (for existing MediaInfo) updates will upload to Wikibase without duplication, but a Statement update will be duplicated on both Items and MediaInfo entities if an equal Statement is already present.
This is a regression from the previous `editor.updateTermsStatements` api.

**Comment by wetneb** [comment]
@robertvazan we encountered the problem above while migrating to the new API in OpenRefine. I wonder if the change is intentional, i.e. if we should re-implement de-duplication on our side, or if it is worth adding back to WTDK?

**Comment by robertvazan** [comment]
Merge logic was indeed omitted for being application-specific. Or more precisely, there was this idea that pluggable merge strategies would be later added to the API. The API nevertheless allows you to ensure that no duplicate statements are added, but all the merge logic must be on application side for now. I could be more specific given some sample code.

**Comment by wetneb** [comment]
That makes total sense, as you know this is something I wanted to work on anyway. We can reimplement something on our side for now, and push it to WDTK if it feels ripe for it.

**Comment by wetneb** [comment]
I am working on reimplementing this on OpenRefine's side.
