### ISSUE TITLE
Migrate to <dependencyManagement> to control versions of dependencies

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#706]
We currently use Maven properties in the root POM to specify the versions of our dependencies, but that only works to control the versions of the dependencies that are directly mentioned in submodules. Using the <dependencyManagement> section would instead let us control the versioning of transitive dependencies as well.

Is that correct @robertvazan?

**Comment by robertvazan** [comment]
I am using dependency management simply to keep versions in parent POM, but maven docs indeed say that transitive dependencies can be controlled this way too. That's a plus, AFAICT.
