### ISSUE TITLE
Remove datatype IRI from Wikibase data model implementation

### ISSUE THREAD

**Issue by Tpt** [Wikidata/Wikidata-Toolkit#718]
Datatype IRIs are not native to the Wikibase Data Model. They crease a lot of problems like #716.

We might replace the  `DatatypeIdValue` IRI field with a new field storing the JSON datatype ID.

The IRI support would be moved to the RDF module and stay there.

Migration path:
1. Merge #717
2. Deprecate the IRI field of the DatatypeIdValue
3. After one or two release, drop the IRI field.
4. Migration done!

**Comment by wetneb** [comment]
I am obviously very tempted by that plan.
I was assuming that the IRI field was somehow needed by wdtk-rdf, perhaps. In that case it might be possible to just push this into that module instead.
