### ISSUE TITLE
Rename to Wikibase-Toolkit or something else?

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#737]
Since this library is not particularly specific to Wikidata but applies to all Wikibases, perhaps it would be named differently. "Wikibase-Toolkit" could be an option, but perhaps it would be worth using a name which indicates a bit more clearly that it is a Java library.
Thoughts?

**Comment by Tpt** [comment]
That's a great question! Indeed, a more Java-related and Wikibase name would be better. But is the renaming worth the hassle?

**Comment by wetneb** [comment]
Let's say it's not worth the effort :+1:
