### ISSUE TITLE
Why does wdt use /other/wikidata/ instead of /wikidatawiki/entities/?

### ISSUE THREAD

**Issue by devlperry** [Wikidata/Wikidata-Toolkit#759]
Apologies if this is a dumb question, only just learning the ropes of wikidata. I ran into problems downloading dumps in the examples and with a bit of debugging found that the json it was downloading from https://dumps.wikimedia.org/other/wikidata/ were 100% lexemes and thus process 0 results when processed. Seems the dumps that happen there alternate between items(?) and lexemes, which is obvious from the filesizes. There's nothing to differentiate between the files unfortunately.

Looking through the wikidata site it seems https://dumps.wikimedia.org/wikidatawiki/entities/ is the correct directory for json dumps, and all the files there are nicely ordered and can be accessed programmatically. It honestly seems to me like /other/wikidata has long since been abandoned, most of the files there are empty. Is there some technical reason wdt is still using it?

**Comment by wetneb** [comment]
Hi @devlperry, that makes a lot of sense! Would you be up for making a PR which fixes this?

**Comment by devlperry** [comment]
The more I look at it, the more broken it seems. Very few of the end points for dumps seem to work out of the box. A lot of settings seem like they would benefit from being in a properties file rather than hard coded.  Looking through git it seems most of this hasn't been touched for 8-9 years. Lot's of changes are needed to the point where it's seems easier to start a new project so there are no broken dependencies.

**Comment by wetneb** [comment]
Ok! I am indeed not using the wdtk-dumpfiles module at all personally. The wdtk-datamodel and wdtk-wikibaseapi modules are actively used and maintained (because I need them in [OpenRefine](https://github.com/OpenRefine/OpenRefine)).

Perhaps it would be worth removing wdtk-dumpfiles if it gives such a bad impression on the overall project.
