### ISSUE TITLE
WbGetEntitiesAction cannot search media-info for titles containing "-"

### ISSUE THREAD

**Issue by don-vip** [Wikidata/Wikidata-Toolkit#777]
This code fails to retrieve the media-info for [this file](https://commons.wikimedia.org/wiki/File:IAU_2006_General_Assembly-_Result_of_the_IAU_Resolution_Votes_(iau0603d).jpg):
```java
@Test
void testGetMediaInfoDocument() throws Exception {
    assertNotNull(WikibaseDataFetcher.getWikimediaCommonsDataFetcher().getEntityDocumentByTitle(
            "commonswiki", 
            "File:IAU_2006_General_Assembly-_Result_of_the_IAU_Resolution_Votes_(iau0603d).jpg"));
}
```

It's because of this split, [line 169](https://github.com/Wikidata/Wikidata-Toolkit/blame/master/wdtk-wikibaseapi/src/main/java/org/wikidata/wdtk/wikibaseapi/WbGetEntitiesAction.java#L169):
```java
List<String> titlesList = titles == null ? Collections.emptyList() : Arrays.asList(titles.split("-"));
```

As the file name contains a dash, the map key does not match the full title.

**Comment by don-vip** [comment]
As a workaround I use this hack:

```java
    static MediaInfoDocument getMediaInfoDocument(String filename) throws MediaWikiApiErrorException, IOException {
        // workaround to https://github.com/Wikidata/Wikidata-Toolkit/issues/777
        String title = "File:" + filename;
        if (fetcher.getEntityDocumentsByTitle("commonswiki", title)
                .get(title.split("-")[0]) instanceof MediaInfoDocument doc) {
            return doc;
        } else {
            throw new IllegalStateException("No commons mediaInfo found for filename " + filename);
        }
    }
```

**Comment by wetneb** [comment]
Thanks @don-vip! What a honor to have a JOSM developer in this modest repository! :)

This `titles.split("-")` should just be `titles.split("|")`. Titles cannot contain the `|` character and this is the one that is used to encode lists of parameters in this API. See https://commons.wikimedia.org/w/api.php?action=help&modules=wbgetentities

**Comment by don-vip** [comment]
Hi @wetneb, thank you! You're welcome, thank you for the quick fix 👍
