### ISSUE TITLE
Missing linkage between generated properties

### ISSUE THREAD

**Issue by styner0305** [Wikidata/Wikidata-Toolkit#84]
We are trying to use RDF data from WikiDataToolKit, and we noticed the generated properties like those shown below:

original property              generated properties
ns : P01230            ->           ns: P01230c 
ns : P01230            ->           ns: P01230s
ns : P01230            ->           ns: P01230v
ns : P01230            ->           ns: P01230r
ns : P01230            ->           ns: P01230q

We have found out that there were no linkages between original properties and generated properties. Actually we would like to use some information such as labels, descriptions from original properties, so we think there could be an addition
to org.wikidata.wdtk.rdf.OwlDeclarationBuffer.writePropertyDeclarations(), which makes some links such as:

<http://www.wikidata.org/entity/P1230>  ns:simpleClaimProperty <http://www.wikidata.org/entity/P1230c>

Thank you for making the toolkit.

**Comment by joernhees** [comment]
i'd love this too...

i just loaded the recent dumps into our virtuoso server, but found that i need to rewrite the IRIs to get to the labels of the properties... this is pretty slow and complicated compared to a lookup... also that rewriting itself is knowledge that is only there implicitly at the moment.

**Comment by joernhees** [comment]
cool, thanks ;)

will this make it into the next dump already?

**Comment by mkroetzsch** [comment]
Yes, it should.

By the way, while this took a while to implement in WDTK, your feature request has long influenced our ongoing discussion with the Wikimedia Foundation, and the official RDF dumps will contain suitable links as well. We will align with the official dumps in due course (there are some other changes), but in the mid term there will also be official RDF dumps provided by Wikdata (there are experimental ones already), and the WDTK dumps will hopefully no longer be needed then. We might use WDTK to build custom dumps or dumps with additional data integrated.
