### ISSUE TITLE
Bug with date value IDs

### ISSUE THREAD

**Issue by jiwoo35** [Wikidata/Wikidata-Toolkit#85]
I am a researcher from KAIST SWRC(Semantic Web Research Center).
Our team is working for making RDF repository referencing to Wikidata.
We have been looking at data from simple statement and full statement. 
We found one bug in RDF data, where the simple statement file and full statement file have two different dates from the same generated ID. This could cause a problem when incorporating data from simple statement and ones from full statement.

For example, date from full statement, <http://www.wikidata.org/entitiy/VT74cee5440e7c65414d6c62820efa3dc2> 
 <http://www.wikidata.org/ontology#time> 
"1991-11-25""^^<http://www.w3.org/2001/XMLSchema#date> .

date from simple statement
<http://www.wikidata.org/entity/VT74cee5440e7c65414d6c62820efa3dc2> <http://www.wikidata.org/ontology#time> 
"1942-11-26"^^<http://www.w3.org/2001/XMLSchema#date> .

The problem may be in the digest function in Vocabulary.java in getTimeValueUri function.

Currently, it's not an urgent problem for us.

**Comment by fer-rum** [comment]
Is this still valid?

**Comment by mkroetzsch** [comment]
Based on recent tests in an RDF store, I suspect that this bug still exists. Investigation needed.

**Comment by jacekkopecky** [comment]
I can't quickly test it, sorry.
Jack

**Comment by mkroetzsch** [comment]
The problem seems to occur in the current RDF dumps. For example, our recent dump had far too many uses of TimeValue with local name "VT0561f43b8c61ffb6e17cc3b957793f1f". You can make a list of these uses with the following query at the [Wikidata SPARQL endpoint](http://milenio.dcc.uchile.cl/sparql):

```
PREFIX : <http://www.wikidata.org/entity/>
SELECT *
WHERE {
  ?s ?p :VT0561f43b8c61ffb6e17cc3b957793f1f .
}
```

The data of the TimeValue as such is displayed with

```
PREFIX : <http://www.wikidata.org/entity/>
SELECT *
WHERE {
  :VT0561f43b8c61ffb6e17cc3b957793f1f ?p ?o .
}
```

**Comment by mkroetzsch** [comment]
The dump has systematically associated wrong data with value ids of times, coordinates, and numbers (quantities). The error only occurred if an item was using the exact same value as another item did before *and* in addition contained further values after that. This is why mostly times were affected (coordinates probably never had this situation, quantities could have had them in rare cases only). The resulting RDF contained the correct number of values and the correct properties, but (in the affected cases) the wrong details to certain values.

Current RDF dumps are still affected and will be updated in due course.
