### ISSUE TITLE
JsonConverter - JSONException

### ISSUE THREAD

**Issue by bolatov** [Wikidata/Wikidata-Toolkit#89]
I guess there is a bug in [JsonConverter](https://github.com/Wikidata/Wikidata-Toolkit/blob/master/wdtk-dumpfiles/src/main/java/org/wikidata/wdtk/dumpfiles/JsonConverter.java) class. At line 179 it expects "claims" to be a JSONArray, in fact it is a JSONObject.

```java
if (jsonObject.has(KEY_CLAIM)) {
    JSONArray jsonStatements = jsonObject.getJSONArray(KEY_CLAIM);
    statements = this.getStatementGroups(jsonStatements, itemId);
}
```

**Comment by fer-rum** [comment]
Since no further discussion is taking olace, I close this for now. Re-open, if necessary.
